language: java
arch: ppc64le
branches:
  only:
  - master
  - /^\d+\.\d+$/
addon:
  apt:
    - openssl
    - ninja-build
    - golang
    - libapr1
    - libapr1-dev
    - libssl-dev
    - cmake
    - autoconf
    - libtool
  
before_install:
  - sudo ./Setup_maven.sh >/dev/null 2>&1
  - source /etc/profile.d/maven.sh
  - ./Install_hawtjni.sh >/dev/null 2>&1
  - ./Install_netty_tcnative.sh >/dev/null 2>&1
  - ./Install_netty.sh
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/io/vertx/
jobs:
  include:
    - stage: test
      name: "OpenJDK 8"
      jdk: openjdk8
      script: mvn -q clean verify -B
      install: . ./install-jdk.sh --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=linux&type=jdk&release=latest&heap_size=normal&arch=ppc64le"
notifications:
  email:
    recipients:
      - secure: "V3kSlUMaHLlFhnbGa567mdKv1/d4iPLHJEWi1llFDeLhu+pJsAGOZOFqr6bN9V0PJIdCGzr9/xqauA2kdunnqICM8iLga0/vvjZWB/G1SXrmPsL820szvU3Id/BLBJzbnZWPNbmMCSyFLgkUuAJ6QLMFGH56RqUst65Z2++VzHU="
    on_success: always
    on_failure: always
